server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam
    driver-class-name: org.postgresql.Driver
    username: iamuser
    password: iampass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  expiration: 3600

oauth:
  issuer: "http://localhost:8080"
  clients:
    - clientId: "sample-client"
      clientSecret: "secret"
      redirectUris: ["http://localhost:3000/callback"]
      scopes: ["openid","profile"]
      confidential: true

saml:
  metadataLocation: "classpath:saml/metadata.xml"
logging:
  level:
    org.springframework.security: DEBUG
    com.example.iam: DEBUG
    org.springframework.web: DEBUG